// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consignment/consignment.proto

package consignment // import "proto/consignment"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import status "google.golang.org/genproto/googleapis/rpc/status"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateConsignmentRequest struct {
	Consignments         []*Consignment `protobuf:"bytes,1,rep,name=consignments,proto3" json:"consignments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateConsignmentRequest) Reset()         { *m = CreateConsignmentRequest{} }
func (m *CreateConsignmentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateConsignmentRequest) ProtoMessage()    {}
func (*CreateConsignmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_0513dacc6ec3c34d, []int{0}
}
func (m *CreateConsignmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConsignmentRequest.Unmarshal(m, b)
}
func (m *CreateConsignmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConsignmentRequest.Marshal(b, m, deterministic)
}
func (dst *CreateConsignmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConsignmentRequest.Merge(dst, src)
}
func (m *CreateConsignmentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateConsignmentRequest.Size(m)
}
func (m *CreateConsignmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConsignmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConsignmentRequest proto.InternalMessageInfo

func (m *CreateConsignmentRequest) GetConsignments() []*Consignment {
	if m != nil {
		return m.Consignments
	}
	return nil
}

type CreateConsignmentResponse struct {
	Status               []*status.Status `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
	Consignments         []*Consignment   `protobuf:"bytes,2,rep,name=consignments,proto3" json:"consignments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateConsignmentResponse) Reset()         { *m = CreateConsignmentResponse{} }
func (m *CreateConsignmentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateConsignmentResponse) ProtoMessage()    {}
func (*CreateConsignmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_0513dacc6ec3c34d, []int{1}
}
func (m *CreateConsignmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConsignmentResponse.Unmarshal(m, b)
}
func (m *CreateConsignmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConsignmentResponse.Marshal(b, m, deterministic)
}
func (dst *CreateConsignmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConsignmentResponse.Merge(dst, src)
}
func (m *CreateConsignmentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateConsignmentResponse.Size(m)
}
func (m *CreateConsignmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConsignmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConsignmentResponse proto.InternalMessageInfo

func (m *CreateConsignmentResponse) GetStatus() []*status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CreateConsignmentResponse) GetConsignments() []*Consignment {
	if m != nil {
		return m.Consignments
	}
	return nil
}

type GetConsignmentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConsignmentRequest) Reset()         { *m = GetConsignmentRequest{} }
func (m *GetConsignmentRequest) String() string { return proto.CompactTextString(m) }
func (*GetConsignmentRequest) ProtoMessage()    {}
func (*GetConsignmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_0513dacc6ec3c34d, []int{2}
}
func (m *GetConsignmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConsignmentRequest.Unmarshal(m, b)
}
func (m *GetConsignmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConsignmentRequest.Marshal(b, m, deterministic)
}
func (dst *GetConsignmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConsignmentRequest.Merge(dst, src)
}
func (m *GetConsignmentRequest) XXX_Size() int {
	return xxx_messageInfo_GetConsignmentRequest.Size(m)
}
func (m *GetConsignmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConsignmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConsignmentRequest proto.InternalMessageInfo

func (m *GetConsignmentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetConsignmentResponse struct {
	Status               *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Consignments         *Consignment   `protobuf:"bytes,2,opt,name=consignments,proto3" json:"consignments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetConsignmentResponse) Reset()         { *m = GetConsignmentResponse{} }
func (m *GetConsignmentResponse) String() string { return proto.CompactTextString(m) }
func (*GetConsignmentResponse) ProtoMessage()    {}
func (*GetConsignmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_0513dacc6ec3c34d, []int{3}
}
func (m *GetConsignmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConsignmentResponse.Unmarshal(m, b)
}
func (m *GetConsignmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConsignmentResponse.Marshal(b, m, deterministic)
}
func (dst *GetConsignmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConsignmentResponse.Merge(dst, src)
}
func (m *GetConsignmentResponse) XXX_Size() int {
	return xxx_messageInfo_GetConsignmentResponse.Size(m)
}
func (m *GetConsignmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConsignmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConsignmentResponse proto.InternalMessageInfo

func (m *GetConsignmentResponse) GetStatus() *status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetConsignmentResponse) GetConsignments() *Consignment {
	if m != nil {
		return m.Consignments
	}
	return nil
}

type ListConsignmentRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListConsignmentRequest) Reset()         { *m = ListConsignmentRequest{} }
func (m *ListConsignmentRequest) String() string { return proto.CompactTextString(m) }
func (*ListConsignmentRequest) ProtoMessage()    {}
func (*ListConsignmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_0513dacc6ec3c34d, []int{4}
}
func (m *ListConsignmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListConsignmentRequest.Unmarshal(m, b)
}
func (m *ListConsignmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListConsignmentRequest.Marshal(b, m, deterministic)
}
func (dst *ListConsignmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListConsignmentRequest.Merge(dst, src)
}
func (m *ListConsignmentRequest) XXX_Size() int {
	return xxx_messageInfo_ListConsignmentRequest.Size(m)
}
func (m *ListConsignmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListConsignmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListConsignmentRequest proto.InternalMessageInfo

type ListConsignmentResponse struct {
	Status               []*status.Status `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
	Consignments         []*Consignment   `protobuf:"bytes,2,rep,name=consignments,proto3" json:"consignments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListConsignmentResponse) Reset()         { *m = ListConsignmentResponse{} }
func (m *ListConsignmentResponse) String() string { return proto.CompactTextString(m) }
func (*ListConsignmentResponse) ProtoMessage()    {}
func (*ListConsignmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_0513dacc6ec3c34d, []int{5}
}
func (m *ListConsignmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListConsignmentResponse.Unmarshal(m, b)
}
func (m *ListConsignmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListConsignmentResponse.Marshal(b, m, deterministic)
}
func (dst *ListConsignmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListConsignmentResponse.Merge(dst, src)
}
func (m *ListConsignmentResponse) XXX_Size() int {
	return xxx_messageInfo_ListConsignmentResponse.Size(m)
}
func (m *ListConsignmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListConsignmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListConsignmentResponse proto.InternalMessageInfo

func (m *ListConsignmentResponse) GetStatus() []*status.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListConsignmentResponse) GetConsignments() []*Consignment {
	if m != nil {
		return m.Consignments
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateConsignmentRequest)(nil), "shippy.consignment.CreateConsignmentRequest")
	proto.RegisterType((*CreateConsignmentResponse)(nil), "shippy.consignment.CreateConsignmentResponse")
	proto.RegisterType((*GetConsignmentRequest)(nil), "shippy.consignment.GetConsignmentRequest")
	proto.RegisterType((*GetConsignmentResponse)(nil), "shippy.consignment.GetConsignmentResponse")
	proto.RegisterType((*ListConsignmentRequest)(nil), "shippy.consignment.ListConsignmentRequest")
	proto.RegisterType((*ListConsignmentResponse)(nil), "shippy.consignment.ListConsignmentResponse")
}

func init() {
	proto.RegisterFile("proto/consignment/consignment.proto", fileDescriptor_consignment_0513dacc6ec3c34d)
}

var fileDescriptor_consignment_0513dacc6ec3c34d = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xce, 0xcf, 0x2b, 0xce, 0x4c, 0xcf, 0xcb, 0x4d, 0xcd, 0x2b, 0x41, 0x66, 0xeb,
	0x81, 0x65, 0x85, 0x84, 0x8a, 0x33, 0x32, 0x0b, 0x0a, 0x2a, 0xf5, 0x90, 0x64, 0xa4, 0xc4, 0xd3,
	0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5, 0x8b, 0x0a, 0x92, 0xf5, 0x8b, 0x4b, 0x12, 0x4b, 0x4a, 0x8b,
	0x21, 0x8a, 0xa5, 0x64, 0x31, 0x4d, 0xcc, 0x2c, 0x49, 0xcd, 0x85, 0x4a, 0x2b, 0xc5, 0x73, 0x49,
	0x38, 0x17, 0xa5, 0x26, 0x96, 0xa4, 0x3a, 0x23, 0x14, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97,
	0x08, 0x39, 0x73, 0xf1, 0x20, 0x69, 0x2b, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0x92, 0xd7,
	0xc3, 0xb4, 0x5e, 0x0f, 0x59, 0x37, 0x8a, 0x26, 0xa5, 0x1e, 0x46, 0x2e, 0x49, 0x2c, 0x36, 0x14,
	0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x69, 0x71, 0xb1, 0x41, 0x5c, 0x0b, 0x35, 0x5c, 0x48, 0x0f,
	0xe2, 0x0f, 0xbd, 0xa2, 0x82, 0x64, 0xbd, 0x60, 0xb0, 0x4c, 0x10, 0x54, 0x05, 0x86, 0x73, 0x98,
	0xc8, 0x71, 0x8e, 0x3a, 0x97, 0xa8, 0x7b, 0x6a, 0x09, 0x16, 0xcf, 0xf2, 0x71, 0x31, 0x65, 0xa6,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x31, 0x65, 0xa6, 0x28, 0x75, 0x32, 0x72, 0x89, 0xa1,
	0xab, 0xc4, 0xe2, 0x68, 0x46, 0x92, 0x1d, 0xcd, 0x48, 0xba, 0xa3, 0x25, 0xb8, 0xc4, 0x7c, 0x32,
	0x8b, 0xb1, 0xb8, 0x5a, 0xa9, 0x8b, 0x91, 0x4b, 0x1c, 0x43, 0x6a, 0x80, 0xc2, 0xd6, 0x49, 0x38,
	0x4a, 0x10, 0x23, 0xb1, 0x25, 0xb1, 0x81, 0x85, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x07,
	0xe4, 0xcc, 0x08, 0xda, 0x02, 0x00, 0x00,
}
