// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consignment/items.proto

package consignment // import "proto/consignment"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 货轮承运的一批货物
type Consignment struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight               int32        `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	VesselId             string       `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_items_381eeff0d6928aff, []int{0}
}
func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (dst *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(dst, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

// 单个集装箱
type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_items_381eeff0d6928aff, []int{1}
}
func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (dst *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(dst, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterType((*Consignment)(nil), "shippy.consignment.Consignment")
	proto.RegisterType((*Container)(nil), "shippy.consignment.Container")
}

func init() {
	proto.RegisterFile("proto/consignment/items.proto", fileDescriptor_items_381eeff0d6928aff)
}

var fileDescriptor_items_381eeff0d6928aff = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x3f, 0x4b, 0xc4, 0x40,
	0x10, 0xc5, 0x49, 0xee, 0x8f, 0x66, 0x02, 0x82, 0x23, 0xe8, 0x82, 0x1c, 0x86, 0xab, 0x52, 0xe5,
	0x40, 0x6b, 0x1b, 0xaf, 0x4a, 0x9b, 0xd2, 0x46, 0x34, 0x3b, 0xe4, 0x06, 0xcc, 0x6e, 0xd8, 0xd9,
	0x53, 0xfc, 0x5c, 0x7e, 0x41, 0xc9, 0xe6, 0xe2, 0x05, 0x52, 0xbe, 0xdf, 0xdb, 0xc7, 0xfe, 0x18,
	0xd8, 0x74, 0xce, 0x7a, 0xbb, 0xab, 0xad, 0x11, 0x6e, 0x4c, 0x4b, 0xc6, 0xef, 0xd8, 0x53, 0x2b,
	0x45, 0xe0, 0x88, 0x72, 0xe0, 0xae, 0xfb, 0x29, 0x26, 0xfd, 0xf6, 0x37, 0x82, 0x74, 0x7f, 0xce,
	0x78, 0x05, 0x31, 0x6b, 0x15, 0x65, 0x51, 0x9e, 0x54, 0x31, 0x6b, 0xcc, 0x20, 0xd5, 0x24, 0xb5,
	0xe3, 0xce, 0xb3, 0x35, 0x2a, 0x0e, 0xc5, 0x14, 0xe1, 0x2d, 0xac, 0xbf, 0x89, 0x9b, 0x83, 0x57,
	0x8b, 0x2c, 0xca, 0x57, 0xd5, 0x29, 0xe1, 0x33, 0x40, 0x6d, 0x8d, 0x7f, 0x67, 0x43, 0x4e, 0xd4,
	0x32, 0x5b, 0xe4, 0xe9, 0xe3, 0xa6, 0x98, 0x2b, 0x14, 0xfb, 0xf1, 0x55, 0x35, 0x19, 0xe0, 0x3d,
	0x24, 0x5f, 0x24, 0x42, 0x9f, 0x6f, 0xac, 0xd5, 0x2a, 0x7c, 0x7b, 0x39, 0x80, 0x52, 0x6f, 0x5b,
	0x48, 0xfe, 0x57, 0x33, 0xe5, 0x07, 0x48, 0xeb, 0xa3, 0x78, 0xdb, 0x92, 0xeb, 0xb7, 0x83, 0x32,
	0x8c, 0xa8, 0xd4, 0xbd, 0xb1, 0x75, 0xdc, 0xb0, 0x09, 0xc6, 0x49, 0x75, 0x4a, 0x78, 0x07, 0x17,
	0x47, 0x19, 0x46, 0xcb, 0xa1, 0xe8, 0x63, 0xa9, 0x5f, 0x6e, 0x5e, 0xaf, 0x67, 0x97, 0xfd, 0x58,
	0x07, 0xf4, 0xf4, 0x17, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x8c, 0x83, 0x80, 0x75, 0x01, 0x00, 0x00,
}
